--code for the main window of NeoStats

local utils = require("neostats.window.utils") --import util functions
local data = require("neostats.data") --get data for project

local M = {}

M.window = { --table for window opts
	buf = nil,
	win = nil,
	width = function() --calculate width on window.width()
		return math.floor(vim.o.columns * 0.5)
	end,
	height = function() --same for height
		return math.floor(vim.o.lines * 0.8)
	end,
}

--create main window (takes in stats table for displaying)
function M.open()
	local width = M.window.width() --calculate width and height
	local height = M.window.height()

	local buf = vim.api.nvim_create_buf(false, true) --buffer
	vim.api.nvim_buf_set_lines(buf, 0, -1, false, M.gen_text(width)) --set initial window text

	local win = vim.api.nvim_open_win(buf, true, { --open win and get focus
		relative = "editor",
		anchor = "NW", --NW so that top left of window is placed at row,col
		width = width,
		height = height,
		row = math.floor((vim.o.lines - height) / 2) - vim.o.cmdheight, --account for cmdline
		col = math.floor((vim.o.columns - width) / 2),
		style = "minimal",
		border = "rounded",
		title = " NeoStats ", --title and footer, centered
		title_pos = "center",
		footer = " NeoStats ",
		footer_pos = "center",
	})

	M.window.buf = buf --store references to buffer and window
	M.window.win = win

	vim.bo[M.window.buf].modifiable = false --make not modifiable
	vim.bo[M.window.buf].readonly = false --but still interactable

	--keymap for closing window with q
	vim.keymap.set("n", "q", function()
		M.close()
	end, { buffer = M.window.buf, nowait = true })
end

--close main window
function M.close()
	if M.exists() then --if window exists
		vim.api.nvim_win_close(M.window.win, true) --close window
		vim.api.nvim_buf_delete(M.window.buf, { force = true }) --delete buffer
		M.window.win = nil --delete references
		M.window.buf = nil
	end
end

--check if main window exists
function M.exists()
	if M.window.win and M.window.buf then --if exists
		if vim.api.nvim_win_is_valid(M.window.win) and vim.api.nvim_buf_is_valid(M.window.buf) then
			return true --return true if valid
		end
	else
		return false
	end
end

--generate text for main window. width is the width of the text
function M.gen_text(width)
	local lines = {
		utils.center("Your super cool NeoVim stats", width),
		"", --blank line
		utils.center( --total chars added/deleted
			M.format_stat(
				"Chars Typed/Deleted",
				data.project.stats.total_chars .. "/" .. data.project.stats.total_deleted_chars,
				math.floor(width / 1.5)
			),
			width
		),
		utils.center( --total time in project
			M.format_stat("Total Time", utils.time_format(data.project.stats.total_time), math.floor(width / 1.5)),
			width
		),
	}

	--all chars table
	local char_lines = M.format_all_chars(data.project.stats.all_chars, width) --format all chars into table of lines
	for i, v in ipairs(char_lines) do --for each line returned from format
		table.insert(lines, v) --put into lines table
	end

	return lines
end

--format the all_chars section of the stats table
function M.format_all_chars(value, width)
	local lines = {} --lines that will be generated by this function
	table.insert(lines, "") --blank lines
	table.insert(lines, utils.center("Top 10 Characters", width)) --title
	local entries = {} --table to track name and value of each character recorded

	for char, count in pairs(value) do --for each char in the all_chars table
		table.insert(entries, { char = char or 0, count = count or 0 }) --put into entries
	end
	table.sort(entries, function(a, b) --sort the entries into order
		return a.count > b.count
	end)

	for i = 1, math.min(10, #entries) do --for top 10 entries (or less if less)
		local e = entries[i] --get single entry
		local line = M.format_stat(e.char, e.count, math.floor(width / 6)) --format line
		table.insert(lines, utils.center(line, width)) --center and insert line
	end
	table.insert(lines, "") --blank line
	return lines --send back lines generated here
end

--formatting for the main window
----width = total width of the text from stat to value
function M.format_stat(stat, value, width)
	local str = string.format("%-" .. (width - #tostring(value)) .. "s%s", stat .. ":", value) --get the formatted string
	--works by taking a width for the whole string and putting stat and value on opposite ends of it
	local before, after = str:match("^(.-:)(.*)$") --split the output into before and after the ":"
	--done to keep names like "total chars" intact when doing the gsub next
	after = after:gsub(" ", ".") --replace the big empty space with dots
	return before .. after --then return the full string with the spaces replaced with dots
end

return M
